# Generated by Django 3.2 on 2021-04-26 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycakes', '0005_alter_cakes_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 11, 41, 52, 163971)),
        ),
    ]
