# Generated by Django 3.2 on 2021-04-27 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycakes', '0021_alter_cakes_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 13, 7, 33, 396460)),
        ),
    ]
