# Generated by Django 3.2 on 2021-04-28 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycakes', '0022_alter_cakes_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='createdat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
