# Generated by Django 3.2 on 2021-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mycakes', '0003_alter_cakes_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('cart', models.ManyToManyField(to='mycakes.Cakes')),
            ],
        ),
    ]
