# Generated by Django 3.2 on 2021-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycakes', '0004_alter_cakes_createdat'),
        ('usercakes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='mycakes.Cakes'),
        ),
    ]
