# Generated by Django 3.2 on 2021-04-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycakes', '0006_alter_cakes_createdat'),
        ('usercakes', '0002_auto_20210424_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('mode', models.CharField(default='cash', max_length=250)),
                ('pending', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('cakes', models.ManyToManyField(blank=True, null=True, to='mycakes.Cakes')),
            ],
        ),
    ]
