# Generated by Django 3.2 on 2021-04-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycakes', '0008_alter_cakes_createdat'),
        ('usercakes', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(blank=True, to='mycakes.Cakes'),
        ),
    ]
