# Generated by Django 3.2 on 2021-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercakes', '0008_auto_20210426_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
