# Generated by Django 3.2 on 2021-04-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercakes', '0009_auto_20210426_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
