# Generated by Django 3.2 on 2021-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercakes', '0012_auto_20210426_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(blank=True, default='cash', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
